services:
  rodb-app_proxy:
    image: getumbrel/app-proxy:1.0.0
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_HOST=rodb-gopool-container
      - APP_PORT=80
      - MANAGER_IP=${UMBREL_MANAGER_IP:-10.21.0.1}
      - UMBREL_AUTH_SECRET=${UMBREL_AUTH_SECRET}
    container_name: rodb-gopool_app_proxy_1
    networks:
      - umbrel_main_network
  rodb-gopool:
    image: rodb2008com/gopool-multi:v0.2.7-Multi-RodB0
    container_name: rodb-gopool-container
    restart: unless-stopped
    ports:
      - '8001:80'
      - '6001:6001'
      - '24401:24401'
    volumes:
      - /home/umbrel/umbrel/app-data/rodb-dgb-goPool/data:/app/data
      - /home/umbrel/umbrel/app-data/rodb-dgb-goPool/scripts:/app/scripts
      - /home/umbrel/umbrel/app-data/rodb-dgb-goPool/logo.png:/app/logo.png:ro
      - /home/umbrel/umbrel/app-data/bitcoin/data/bitcoin/:/home/umbrel/:ro
    environment:
      - APP_ENV=production
      - PORT=80
      - MANAGER_IP=${UMBREL_MANAGER_IP:-10.21.0.1}
      - UMBREL_AUTH_SECRET=${UMBREL_AUTH_SECRET}
    command: ["-network=dgb", "-allow-rpc-creds"]
    networks:
      - umbrel_main_network
  rodb-gopool-widget:
    image: rodb2008com/gopool-api-etl:latest
    entrypoint: /bin/sh -c "sleep 20 && exec gunicorn --bind 0.0.0.0:23000 app:app"
    restart: unless-stopped
    container_name: rodb-gopool-widget_1
    ports:
      - '23001:23000'
    extra_hosts:
      - clerk.clerk.dev:127.0.0.1
      - host.docker.internal:host-gateway
    networks:
      - umbrel_main_network
networks:
  umbrel_main_network:
    external: true

